version: "3.9"
services:
  db:
    image: postgres:14.8
    command: postgres -c 'max_connections=200'
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=fanimator"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - REDIS_URL=redis://passmaster-redis:6379/0
    volumes:
      - .:/app
  redis:
    image: redis:latest
    container_name: passmaster-redis
    ports:
      - "6379:6379"