apiVersion: v1
kind: Pod
metadata:
  name: passmaster
spec:
  containers:
    - name: passmaster-image
      image: gcr.io/passmaster-389912/passmaster-image:latest
      imagePullPolicy: Always
      livenessProbe:
        httpGet:
          path: /api/v1/passmaster/
          port: 8000
        initialDelaySeconds: 5
        timeoutSeconds: 1
        periodSeconds: 10
        failureThreshold: 3

