"""update migration

Revision ID: 208920c90a20
Revises: f3f7b4ca09ae
Create Date: 2023-06-16 14:52:01.977419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208920c90a20'
down_revision = 'f3f7b4ca09ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
