"""upgrade schemas

Revision ID: 51946e44bf85
Revises: 6df011e94762
Create Date: 2023-06-16 21:59:43.646266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51946e44bf85'
down_revision = '6df011e94762'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('aes_key', sa.String(), nullable=True))
    op.drop_column('keys', 'hashed_aes_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('hashed_aes_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('keys', 'aes_key')
    # ### end Alembic commands ###
