"""init migration

Revision ID: 5c0aae5f06b4
Revises: 
Create Date: 2023-06-16 11:33:22.376553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0aae5f06b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'keys', ['id'])
    op.create_unique_constraint(None, 'passmasters', ['id'])
    op.create_unique_constraint(None, 'tokens', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tokens', type_='unique')
    op.drop_constraint(None, 'passmasters', type_='unique')
    op.drop_constraint(None, 'keys', type_='unique')
    # ### end Alembic commands ###
