"""upgrade migration

Revision ID: 64aed6281619
Revises: cb0ea6854481
Create Date: 2023-06-17 14:07:42.086203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64aed6281619'
down_revision = 'cb0ea6854481'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
