"""upgrade migration

Revision ID: 7f7dac97362d
Revises: a76c88a63ef2
Create Date: 2023-06-17 00:39:15.189342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f7dac97362d'
down_revision = 'a76c88a63ef2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
