"""upgrade migration

Revision ID: a76c88a63ef2
Revises: 51946e44bf85
Create Date: 2023-06-17 00:18:46.061593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a76c88a63ef2'
down_revision = '51946e44bf85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
