"""upgrade migration

Revision ID: cb0ea6854481
Revises: 7f7dac97362d
Create Date: 2023-06-17 00:40:49.678468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb0ea6854481'
down_revision = '7f7dac97362d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
