"""update relationships

Revision ID: f3f7b4ca09ae
Revises: b0e7916853d5
Create Date: 2023-06-16 14:30:45.187392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3f7b4ca09ae'
down_revision = 'b0e7916853d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('keys', sa.Column('aes_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'keys', ['id'])
    op.drop_column('keys', 'hashed_aes_key')
    op.add_column('passmasters', sa.Column('key_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'passmasters', ['id'])
    op.create_foreign_key(None, 'passmasters', 'keys', ['key_id'], ['id'])
    op.create_unique_constraint(None, 'tokens', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tokens', type_='unique')
    op.drop_constraint(None, 'passmasters', type_='foreignkey')
    op.drop_constraint(None, 'passmasters', type_='unique')
    op.drop_column('passmasters', 'key_id')
    op.add_column('keys', sa.Column('hashed_aes_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'keys', type_='unique')
    op.drop_column('keys', 'aes_key')
    # ### end Alembic commands ###
